name: Test Runner
description: Runs any tests required for the repo.

inputs:
  codecov-token:
    description: Codecov token
    required: true

  package-name:
    description: Package name with changes in PR.
    required: true

  package-directory:
    description: Directory where the package is located.
    required: true

runs:
  using: composite

  steps:
    - name: Run tests with coverage
      shell: bash
      working-directory: ${{ inputs.package-directory }}
      run: |
        dart pub get
        dart run coverage:test_with_coverage

    - name: Track Coverage
      uses: codecov/codecov-action@v5
      with:
        fail_ci_if_error: true
        token: ${{ inputs.codecov-token }}
        disable_search: true
        files: ${{ inputs.package-directory }}/coverage/lcov.info
        flags: ${{ inputs.package-name }}
