name: rookie_yaml
description: A highly configurable parser and dumper for YAML (and optionally json).
version: 0.7.0-pre.2
repository: https://github.com/kekavc24/yaml_dart/tree/main/packages/rookie_yaml
topics:
  - yaml
  - json

platforms:
  android:
  ios:
  linux:
  macos:
  windows:
  web:

resolution: workspace

environment:
  sdk: ^3.9.0

dependencies:
  collection: ^1.19.1
  logging: ^1.3.0
  meta: ^1.18.1

dev_dependencies:
  args: ^2.7.0
  checks: ^0.3.1
  coverage: ^1.15.0
  lints: ^6.1.0
  path: ^1.9.1
  test: ^1.29.0

  # YAML test suite abstraction
  yaml_test_suite_runner:
    git:
      url: https://github.com/kekavc24/yaml_test_suite_runner.git
      ref: 4d5bf04904be073d5f8aecf40327086a784ba56c
